version: '2'
services:
    mim-app:
        image: mim
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://mim-postgresql:5432/mim
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    mim-postgresql:
        extends:
            file: postgresql.yml
            service: mim-postgresql
